apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ms6zca8nw-java-springboot 
  janus-idp.io/tekton: ms6zca8nw-java-springboot
  backstage.io/kubernetes-id: ms6zca8nw-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ms6zca8nw-java-springboot
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml